name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get current tag version
        run: |
          TAG_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0")

      - name: Increment tag version
        run: |
          TAG_VERSION=$((TAG_VERSION + 1))

      - name: Create tag
        run: |
          git tag -a v${TAG_VERSION} -m "New release"
          git push origin v${TAG_VERSION}