name: Create Tag

on:
    push:
        branches:
            - main

jobs:
    create-tag:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                  git config --global user.name "Suvojit Mondal"
                  git config --global user.email "msuvojit@gmail.com"

            - name: Get latest tag
              id: get_latest_tag
              run: |
                  latest_tag=$(git describe --abbrev=0 --tags)
                  echo "::set-output name=latest_tag::$latest_tag"

            - name: Create new tag
              id: create_tag
              run: |
                  latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
                  new_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
                  git tag $new_tag
                  echo "::set-output name=new_tag::$new_tag"

            - name: Push new tag
              run: |
                  new_tag=${{ steps.create_tag.outputs.new_tag }}
                  git push origin $new_tag